# The name of our workflow
name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [openvpn-commit]

jobs:

  msvc:
  
    name: 'cert-test'
    runs-on: windows-2019
    env:
      super_secret: ${{ secrets.SIGNING_CERT123 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Get openvpn commit id
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run:
          $hash = git rev-parse --short HEAD
          echo "OPENPVN_COMMIT=$hash" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    
      - name: Step 0
        if: github.ref == 'refs/heads/main'
        run: |
          Write-Host $Env:OPENPVN_COMMIT
          Write-Host $Env:GITHUB_REF_NAME
          $dt = Get-Date -Format "yyyyMMddhhmmss"
          $sha = '${{ github.event.client_payload.sha }}'.Substring(0, 8)
          Write-Host "openvpn-master-$dt-$sha.msi"
