# The name of our workflow
name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [openvpn-commit]

jobs:

  msvc:
  
    name: 'cert-test'
    runs-on: windows-2019
    env:
      super_secret: ${{ secrets.SIGNING_CERT123 }}

    steps:
      - name: Step 0
        if: $Env:GITHUB_REF_NAME -eq "master"
        run: |
          Write-Host $Env:GITHUB_REF_NAME
          $dt = Get-Date -Format "yyyyMMddhhmmss"
          $sha = '${{ github.event.client_payload.sha }}'.Substring(0, 8)
          Write-Host "openvpn-master-$dt-$sha.msi"
