# The name of our workflow
name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [openvpn-commit]

jobs:

  msvc:
  
    name: 'cert-test'
    runs-on: windows-2019
   
    strategy:
      matrix:
        arch: [x86, amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Produce artifacts
        run: |
         New-Item -Path build-${{ matrix.arch }}
    
      - name: Archieve artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.arch }}

  upload_msis:
    needs: msvc
    name: upload-msis
    runs-on: ubuntu-latest
    
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v3
        
      - name: Check artifacts
        run: ls -la
