# The name of our workflow
name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [openvpn-commit]

jobs:

  msvc:
  
    name: 'cert-test'
    runs-on: windows-2019
    env:
      super_secret: ${{ secrets.SIGNING_CERT123 }}

    steps:
      - name: Step 0
        run: |
          Write-Host ${{ github.event }}
          $dt = Get-Date -Format "yyyyMMddhhmmss"
          $sha = '${{ github.event.client_payload.sha }}'.Substring(0, 8)
          Write-Host "openvpn-master-$dt-$sha.msi"

      - name: Step 1
        if: ${{ env.super_secret != '' }}
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'cert.pfx'
          encodedString: ${{ secrets.SIGNING_CERT }}
    
      - name: Step 2
        if: ${{ env.super_secret != '' }}
        run: Import-PfxCertificate -FilePath ${{ steps.write_file.outputs.filePath }} -CertStoreLocation Cert:\CurrentUser\My -Password (ConvertTo-SecureString -String "${{ secrets.CERT_PASSWORD }}" -Force -AsPlainText)
