# The name of our workflow
name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [openvpn-commit]

jobs:

  msvc:
  
    name: 'cert-test'
    runs-on: windows-2019
   
    strategy:
      matrix:
        arch: [x86, amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Produce artifacts
        run: |
         New-Item -Path build-${{ matrix.arch }}.msi
    
      - name: Archieve artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.arch }}.msi
          path: "*.msi"

  upload_msis:
    needs: msvc
    name: upload-msis
    runs-on: ubuntu-latest
    
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          path: msi
        
      - name: Copy MSI to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: msi
          remote: ${{ secrets.MSI_UPLOAD_REMOTE_PATH }}
          host: ${{ secrets.MSI_UPLOAD_REMOTE_HOST }}
          username: ${{ secrets.MSI_UPLOAD_USERNAME }}
          privateKey: ${{ secrets.MSI_UPLOAD_PRIVATE_KEY }}
          passphrase: ${{ secrets.MSI_UPLOAD_KEY_PASSPHRASE }}
          port: 22622
