# The name of our workflow
name: Build
on:
  push:
  pull_request:

jobs:
  msvc:
  
    name: 'cert-test'
    runs-on: windows-2019

    steps:
      - name: Step 1
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'cert.pfx'
          encodedString: ${{ secrets.SIGNING_CERT }}
    
      - name: Step 2
        run: Import-PfxCertificate -FilePath ${{ steps.write_file.outputs.filePath }} -CertStoreLocation Cert:\CurrentUser\My -Password (ConvertTo-SecureString -String "${{ secrets.CERT_PASSWORD }}" -Force -AsPlainText)
